name: test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.yaml
          kubectl wait --for=condition=available --timeout=60s deployment/cert-manager -n cert-manager
