name: test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: k8slimiter:0.1.0
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.yaml
          kubectl wait --for=condition=available --timeout=60s deployment/cert-manager -n cert-manager
          kubectl wait --for=condition=available --timeout=60s deployment/cert-manager-cainjector -n cert-manager
          kubectl wait --for=condition=available --timeout=60s deployment/cert-manager-webhook -n cert-manager

      - name: Load image into Kind
        run: |
          kind load docker-image k8slimiter:0.1.0

      - name: Install k8slimiter
        run: |
          kubectl apply -f manifests/k8slimiter.yaml
          kubectl wait --for=condition=available --timeout=60s deployment/k8slimiter-deployment -n k8slimiter
          sleep 10

      - name: Test k8slimiter
        run: |
          kubectl run "tmp-pod-$(date +%s)" --restart Never --image debian:12-slim -- sleep 1

          sleep 2
          if kubectl run "tmp-pod-$(date +%s)" --restart Never --image debian:12-slim -- sleep 1; then
            echo "Error: kubectl run command did not exit with status code 1"
            exit 1
          fi

          sleep 10
          kubectl run "tmp-pod-$(date +%s)" --restart Never --image debian:12-slim -- sleep 1
