name: test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
